insert into `setup-tecnorepo`.categoria () values (1,'spring',null);
insert into `setup-tecnorepo`.categoria () values (2,'struts2',null);
insert into `setup-tecnorepo`.categoria(id, nombre, categoria_padre) values (3, "spring-data", 1);
insert into `setup-tecnorepo`.categoria(id, nombre, categoria_padre) values (4, "spring-security", 1);
insert into `setup-tecnorepo`.categoria(id, nombre, categoria_padre) values (5, "spring-cloud", 1);
insert into `setup-tecnorepo`.categoria(id, nombre, categoria_padre) values (6, "spring-boot", 1);
insert into `setup-tecnorepo`.categoria(id, nombre, categoria_padre) values (7, "spring-framework", 1);


insert into `setup-tecnorepo`.miembro (id, nombre, descripcion, categoria_id) values(1, "diferencia entre jpa y spring-data", "Lorem ipsum dolor sit amet consectetur adipiscing elit vulputate nisi nulla, viverra vivamus cum risus rutrum mattis cursus netus fames libero, praesent pretium pellentesque metus dui id lobortis faucibus tempus. Metus bibendum fermentum litora dictum ac nascetur tellus tortor ad imperdiet venenatis, vulputate sollicitudin aliquam nunc id libero nullam sapien risus egestas iaculis, proin scelerisque placerat massa duis ultrices sed montes vehicula tempus. Ut lacinia tellus dis ultrices erat ultricies, class vel hac nam commodo lectus massa, est ornare penatibus et dictum.", 3);
insert into `setup-tecnorepo`.miembro (id, nombre, descripcion, categoria_id) values(2, "diferencia entre jpa y spring-data", "Lorem ipsum dolor sit amet consectetur adipiscing elit vulputate nisi nulla, viverra vivamus cum risus rutrum mattis cursus netus fames libero, praesent pretium pellentesque metus dui id lobortis faucibus tempus. Metus bibendum fermentum litora dictum ac nascetur tellus tortor ad imperdiet venenatis, vulputate sollicitudin aliquam nunc id libero nullam sapien risus egestas iaculis, proin scelerisque placerat massa duis ultrices sed montes vehicula tempus. Ut lacinia tellus dis ultrices erat ultricies, class vel hac nam commodo lectus massa, est ornare penatibus et dictum.", 4);
insert into `setup-tecnorepo`.miembro (id, nombre, descripcion, categoria_id) values(3, "diferencia entre jpa y spring-data", "Lorem ipsum dolor sit amet consectetur adipiscing elit vulputate nisi nulla, viverra vivamus cum risus rutrum mattis cursus netus fames libero, praesent pretium pellentesque metus dui id lobortis faucibus tempus. Metus bibendum fermentum litora dictum ac nascetur tellus tortor ad imperdiet venenatis, vulputate sollicitudin aliquam nunc id libero nullam sapien risus egestas iaculis, proin scelerisque placerat massa duis ultrices sed montes vehicula tempus. Ut lacinia tellus dis ultrices erat ultricies, class vel hac nam commodo lectus massa, est ornare penatibus et dictum.", 2);
insert into `setup-tecnorepo`.miembro (id, nombre, descripcion, categoria_id) values(4, "diferencia entre jpa y spring-data", "Lorem ipsum dolor sit amet consectetur adipiscing elit vulputate nisi nulla, viverra vivamus cum risus rutrum mattis cursus netus fames libero, praesent pretium pellentesque metus dui id lobortis faucibus tempus. Metus bibendum fermentum litora dictum ac nascetur tellus tortor ad imperdiet venenatis, vulputate sollicitudin aliquam nunc id libero nullam sapien risus egestas iaculis, proin scelerisque placerat massa duis ultrices sed montes vehicula tempus. Ut lacinia tellus dis ultrices erat ultricies, class vel hac nam commodo lectus massa, est ornare penatibus et dictum.", 2);